name: Luogu Auto Checkin

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run
        env:
          LUOGU_COOKIE: ${{ secrets.LUOGU_COOKIE }}
          LUOGU_CSRF: ${{ secrets.LUOGU_CSRF }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: node checkin.js
